version: '3'

services:
  api:
    build: .
    container_name: motion_qna_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - USE_TRANSFORMERS=False  # Set to False for faster startup in development
      - DATABASE_URL=sqlite:///motion_qna.db
    command: >
      sh -c "python -c 'from app.core.setup import initialize_app; initialize_app()' &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped 